### ISSUE TITLE
backend-review

### ISSUE THREAD

**Issue by alvin-the-programmer** [HelloPancake/globalMovieFavoriteList#1]
https://github.com/HelloPancake/globalMovieFavoriteList/blob/ede7a644d8ef7dd39ce261072fbfecdb17b6c383/MovieBackEnd/index.js#L13-L19

This route should be a get, not a post. A nice rule of thumb is that post requests must save data to the server. Bonus points if you make this a restful route by making it a get to ' /movie'.

**Comment by alvin-the-programmer** [comment]
https://github.com/HelloPancake/globalMovieFavoriteList/blob/ede7a644d8ef7dd39ce261072fbfecdb17b6c383/MovieBackEnd/index.js#L21-L47

Consider returning inside of the first `if` so that you don't have to have a large else statement.

For restful routing, this endpoint should be post `/favorites` because you are adding to the favorites collection.

**Comment by alvin-the-programmer** [comment]
Reemphasizing my previous comment about the route names since you made a delete 'favorites':

https://github.com/HelloPancake/globalMovieFavoriteList/blob/ede7a644d8ef7dd39ce261072fbfecdb17b6c383/MovieBackEnd/index.js#L55-L66

More consistent to have a GET, POST, DELETE to the same url '/favorites'. Don't fear reusing the url; it is actually preferred to have the same url use different http methods. The logic being that I expect POST, DELETE, GET to '/favorites' to depend on each other, i.e. POSTing to /favorites should directly effect when I GET /favorites after.

A "route" is a combination of HTTP method + url.

**Comment by alvin-the-programmer** [comment]
https://github.com/HelloPancake/globalMovieFavoriteList/blob/ede7a644d8ef7dd39ce261072fbfecdb17b6c383/MovieBackEnd/models/movie.js#L1-L4

Why use `var` here? You use `const` in other files and `const` is more preferred. Start to proactively fix those details. If you make code quality a priority, code correctness will naturally come too.

**Comment by alvin-the-programmer** [comment]
https://github.com/HelloPancake/globalMovieFavoriteList/blob/ede7a644d8ef7dd39ce261072fbfecdb17b6c383/MovieBackEnd/util/fetchMovies.js#L6-L12

I like how this 3rd party function is in a `util/` folder. However, name this function `fetchMovie` not `fetchMovies`. Plurality always gives the signal that the returned data is a collection of many movies, whether that be an array of many movies or an object of many movies. Since the function returns details about a single movie, make it singular.

**Comment by alvin-the-programmer** [comment]
@HelloPancake

**Comment by HelloPancake** [comment]
> https://github.com/HelloPancake/globalMovieFavoriteList/blob/ede7a644d8ef7dd39ce261072fbfecdb17b6c383/MovieBackEnd/index.js#L13-L19
> 
> This route should be a get, not a post. A nice rule of thumb is that post requests must save data to the server. Bonus points if you make this a restful route by making it a get to ' /movie'.

I just tried this but it says get cant have a body
